framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            commands:
                dsn: '%env(MESSENGER_AMQP_TRANSPORT_DSN)%'
                options:
                    queues:
                        booking:commands:
                            binding_keys: ['command.booking.#']
                    exchange:
                        name: amq.topic
                        type: topic
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 10
                serializer: commands_shared_transport_serializer
            events:
                dsn: '%env(MESSENGER_AMQP_TRANSPORT_DSN)%'
                options:
                    queues:
                        booking:events:
                            binding_keys:
                                - 'event.booking.#'
                                - 'event.notification.notification_was_sent'
                    exchange:
                       name: amq.topic
                       type: topic
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 10
                serializer: events_shared_transport_serializer
            queries:
                dsn: '%env(MESSENGER_AMQP_TRANSPORT_DSN)%'
                options:
                    rpc: true
                    queues:
                        booking:queries:
                            binding_keys: ['query.booking.#']
                    exchange:
                        name: amq.topic
                        type: topic
                    connect_timeout: 10
                retry_strategy:
                    max_retries: 0
                serializer: queries_shared_transport_serializer
        routing:
            # Route your messages to the transports
            'Booking\Application\Command\CommandInterface': commands
            'Booking\Application\Query\QueryInterface': queries
            'Booking\Domain\Event\EventInterface': events
        default_bus: command_bus
        buses:
            event_bus:
                default_middleware: 'allow_no_handlers'
                middleware:
                    - dynamic_routing_middleware
            command_bus:
                default_middleware: true
                middleware:
                    - dynamic_routing_middleware
            query_bus:
                default_middleware: true
                middleware:
                    - dynamic_routing_middleware
                    - amqp_extra.rpc_middleware